[package]
name = "rotating_buffer"
version = "0.1.0"
authors = ["eaon <eaon@posteo.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
